<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PublishAot>true</PublishAot>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Godot.Bindings">
      <HintPath>Dll\Godot.Bindings.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="cef.redist.linux64" Version="120.1.8" GeneratePathProperty="true" />
    <PackageReference Include="cef.redist.linuxarm64" Version="120.1.8" GeneratePathProperty="true" />
    <PackageReference Include="CefGlue.Common" Version="120.6099.211" />
    <PackageReference Include="CefGlue.Common.ARM64" Version="120.6099.211" />
    <PackageReference Include="chromiumembeddedframework.runtime" Version="120.1.8" />
    <PackageReference Include="chromiumembeddedframework.runtime.win-x64" Version="120.1.8" />
  </ItemGroup>

</Project>