<Project Sdk="Godot.NET.Sdk/4.6.3">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
	
  <ItemGroup>
    <PackageReference Include="CefGlue.Common" Version="120.6099.211" />
    <PackageReference Include="chromiumembeddedframework.runtime" Version="120.1.8" />
    <PackageReference Include="chromiumembeddedframework.runtime.win-x64" Version="120.1.8" />
  </ItemGroup>
</Project>