<Project Sdk="Godot.NET.Sdk/4.6.3">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <TargetFramework Condition=" '$(GodotTargetPlatform)' == 'android' ">net9.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
	
  <ItemGroup>
    <PackageReference Include="CefGlue.BrowserProcess.runtime.jit" Version="149.7827.156" />
    <PackageReference Include="CefGlue.Common" Version="149.7827.156" />
    <PackageReference Include="chromiumembeddedframework.runtime" Version="149.0.4" />
    <PackageReference Include="chromiumembeddedframework.runtime.win-x64" Version="149.0.4" />
    </ItemGroup>
</Project>