<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PublishAot>true</PublishAot>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup>
    <ExcludeFromProductBuild>true</ExcludeFromProductBuild>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="Godot.Bindings">
      <HintPath>Dll\Godot.Bindings.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CefGlue.Common" Version="134.6998.178" />
    <PackageReference Include="chromiumembeddedframework.runtime.win-x64" Version="145.0.26" />
  </ItemGroup>

  <Target Name="CopyCefFilesToOutput" AfterTargets="Build">
    <PropertyGroup>
      <NuGetPackagesPath>$(NuGetPackageRoot)</NuGetPackagesPath>
      <CefPackagePath>$(NuGetPackagesPath)chromiumembeddedframework.runtime.win-x64\134.3.9\runtimes\win-x64\native\</CefPackagePath>
      <CefLocalesPath>$(NuGetPackagesPath)chromiumembeddedframework.runtime.win-x64\134.3.9\CEF\win-x64\locales\</CefLocalesPath>
      <BrowserProcessPath>$(NuGetPackagesPath)cefglue.common\134.6998.178\bin\win-x64\</BrowserProcessPath>
      <CefOutputPath>$(TargetDir)runtimes\win-x64\native\</CefOutputPath>
      <CefLocalesOutputPath>$(TargetDir)runtimes\win-x64\native\locales\</CefLocalesOutputPath>
      <BrowserProcessSubDir>$(TargetDir)CefGlueBrowserProcess\</BrowserProcessSubDir>
      <RootLocalesPath>$(TargetDir)locales\</RootLocalesPath>
    </PropertyGroup>
    
    <MakeDir Directories="$(CefOutputPath)" />
    <MakeDir Directories="$(CefLocalesOutputPath)" />
    <MakeDir Directories="$(BrowserProcessSubDir)" />
    <MakeDir Directories="$(RootLocalesPath)" />
    
    <ItemGroup>
      <CefNativeFiles Include="$(CefPackagePath)*.*" />
    </ItemGroup>
    
    <Copy SourceFiles="@(CefNativeFiles)" DestinationFolder="$(CefOutputPath)" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(CefNativeFiles)" DestinationFolder="$(TargetDir)" SkipUnchangedFiles="true" />
    
    <ItemGroup>
      <CefLocaleFiles Include="$(CefLocalesPath)*.pak" />
    </ItemGroup>
    
    <Copy SourceFiles="@(CefLocaleFiles)" DestinationFolder="$(CefLocalesOutputPath)" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(CefLocaleFiles)" DestinationFolder="$(RootLocalesPath)" SkipUnchangedFiles="true" />
    
    <ItemGroup>
      <BrowserProcessFiles Include="$(BrowserProcessPath)**\*.*" />
    </ItemGroup>
    
    <Copy SourceFiles="@(BrowserProcessFiles)" DestinationFolder="$(BrowserProcessSubDir)" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(BrowserProcessFiles)" DestinationFolder="$(TargetDir)" SkipUnchangedFiles="true" />
  </Target>

  <Target Name="CopyCefFilesForPublish" AfterTargets="Publish">
    <PropertyGroup>
      <NuGetPackagesPath>$(NuGetPackageRoot)</NuGetPackagesPath>
      <CefPackagePath>$(NuGetPackagesPath)chromiumembeddedframework.runtime.win-x64\134.3.9\runtimes\win-x64\native\</CefPackagePath>
      <CefLocalesPath>$(NuGetPackagesPath)chromiumembeddedframework.runtime.win-x64\134.3.9\CEF\win-x64\locales\</CefLocalesPath>
      <BrowserProcessPath>$(NuGetPackagesPath)cefglue.common\134.6998.178\bin\win-x64\</BrowserProcessPath>
      <CefOutputPath>$(PublishDir)runtimes\win-x64\native\</CefOutputPath>
      <CefLocalesOutputPath>$(PublishDir)runtimes\win-x64\native\locales\</CefLocalesOutputPath>
      <BrowserProcessSubDir>$(PublishDir)CefGlueBrowserProcess\</BrowserProcessSubDir>
      <RootLocalesPath>$(PublishDir)locales\</RootLocalesPath>
    </PropertyGroup>
    
    <MakeDir Directories="$(CefOutputPath)" />
    <MakeDir Directories="$(CefLocalesOutputPath)" />
    <MakeDir Directories="$(BrowserProcessSubDir)" />
    <MakeDir Directories="$(RootLocalesPath)" />
    
    <ItemGroup>
      <CefNativeFiles Include="$(CefPackagePath)*.*" />
    </ItemGroup>
    
    <Copy SourceFiles="@(CefNativeFiles)" DestinationFolder="$(CefOutputPath)" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(CefNativeFiles)" DestinationFolder="$(PublishDir)" SkipUnchangedFiles="true" />
    
    <ItemGroup>
      <CefLocaleFiles Include="$(CefLocalesPath)*.pak" />
    </ItemGroup>
    
    <Copy SourceFiles="@(CefLocaleFiles)" DestinationFolder="$(CefLocalesOutputPath)" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(CefLocaleFiles)" DestinationFolder="$(RootLocalesPath)" SkipUnchangedFiles="true" />
    
    <ItemGroup>
      <BrowserProcessFiles Include="$(BrowserProcessPath)**\*.*" />
    </ItemGroup>
    
    <Copy SourceFiles="@(BrowserProcessFiles)" DestinationFolder="$(BrowserProcessSubDir)" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(BrowserProcessFiles)" DestinationFolder="$(PublishDir)" SkipUnchangedFiles="true" />
  </Target>

</Project>
